name: wixmodular
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.12
  - flask = 3.0.3
  - flask-sqlalchemy = 3.0.1
  - flask-wtf = 1.1.1
  - sqlalchemy = 2.0.25
  - pandas = 2.2.1
  - numpy = 1.26.4
  - seaborn = 0.13.0
  - matplotlib = 3.8.0
  - folium = 0.14.0
  - beautifulsoup4
  - regex = 2023.10.3
  - pip:
    - requests==2.31.0
    - configparser==7.0.0
    - wtforms==3.1.2

